"""
Reality/Simulation Firewall — the hard gate that enforces the central invariant:

    ONLY REALITY PROMOTES.

Two validation tracks:
  - simulation_supported: provisional; may inform; generated by simulations
  - reality_validated: may govern; only earned via reality-scored, pre-registered,
                       out-of-sample predictions

No amount of simulation volume crosses the reality_validated line.
This is enforced in code at the data layer, not in prompts.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from calibration.ledger.prediction_ledger import PredictionRecord

logger = logging.getLogger(__name__)

# Minimum reality-validated predictions required to promote a belief
MIN_REALITY_PREDICTIONS = 3


@dataclass
class Belief:
    belief_id: str
    statement: str
    origin: str                    # principle / theory / agent
    validation_status: str = "provisional"
    sim_support_count: int = 0
    reality_validated_predictions: list[str] = None  # prediction_ids
    promoted_at: Optional[datetime] = None
    created_at: datetime = None

    def __post_init__(self):
        if self.reality_validated_predictions is None:
            self.reality_validated_predictions = []
        if self.created_at is None:
            self.created_at = datetime.now(timezone.utc)


class RealitySimulationFirewall:
    """
    The promotion gate. The ONLY path to reality_validated.

    Beliefs may:
    - Accumulate sim_support_count freely (provisional → simulation_supported)
    - Only reach reality_validated through promote_to_reality_validated()
    - That function enforces: ≥MIN_REALITY_PREDICTIONS resolved TRUE non-post-hoc
      external-source predictions. sim_support_count is IGNORED in the promotion check.
    """

    VALID_STATUSES = {"provisional", "simulation_supported", "reality_validated", "retired"}

    def __init__(self, ledger=None, db=None):
        self._ledger = ledger
        self._beliefs: dict[str, Belief] = {}

    def register_belief(self, belief: Belief) -> str:
        """Register a new belief. Starts as 'provisional'."""
        if belief.validation_status != "provisional":
            raise ValueError(
                f"New beliefs must start as provisional, got {belief.validation_status!r}"
            )
        self._beliefs[belief.belief_id] = belief
        logger.info("BELIEF REGISTERED: id=%s status=provisional origin=%s", belief.belief_id, belief.origin)
        return belief.belief_id

    def add_simulation_support(self, belief_id: str) -> None:
        """
        Record that a simulation supports this belief.
        This may advance provisional → simulation_supported.
        It NEVER advances to reality_validated.
        """
        belief = self._get_belief(belief_id)
        belief.sim_support_count += 1

        if belief.validation_status == "provisional" and belief.sim_support_count >= 3:
            belief.validation_status = "simulation_supported"
            logger.info(
                "BELIEF: %s advanced to simulation_supported (sim_count=%d)",
                belief_id, belief.sim_support_count
            )
        elif belief.validation_status == "reality_validated":
            # Already promoted; sim support is irrelevant
            pass
        else:
            logger.debug(
                "BELIEF: sim support added to %s (count=%d, status=%s)",
                belief_id, belief.sim_support_count, belief.validation_status
            )

    def promote_to_reality_validated(
        self,
        belief_id: str,
        prediction_records: list["PredictionRecord"],
    ) -> bool:
        """
        THE ONLY PATH to reality_validated.

        All checks are enforced here in code. Fails fast with a logged reason
        if any check fails. Simulations cannot promote — sim_support_count is
        explicitly IGNORED in this function.

        Returns True if promoted, False if blocked (with log explaining why).
        """
        belief = self._get_belief(belief_id)

        if belief.validation_status == "reality_validated":
            logger.info("FIREWALL: belief %s is already reality_validated", belief_id)
            return True

        if belief.validation_status == "retired":
            logger.warning("FIREWALL: cannot promote retired belief %s", belief_id)
            return False

        # === GATE 1: Minimum count ===
        if len(prediction_records) < MIN_REALITY_PREDICTIONS:
            logger.warning(
                "FIREWALL BLOCKED: belief %s has %d reality predictions, need %d",
                belief_id, len(prediction_records), MIN_REALITY_PREDICTIONS
            )
            return False

        # === GATE 2: All must be resolved TRUE ===
        unresolved = [p for p in prediction_records if not p.resolved]
        if unresolved:
            logger.warning(
                "FIREWALL BLOCKED: belief %s has %d unresolved predictions",
                belief_id, len(unresolved)
            )
            return False

        false_outcomes = [p for p in prediction_records if p.resolved_outcome is not True]
        if false_outcomes:
            logger.warning(
                "FIREWALL BLOCKED: belief %s has %d predictions with false/null outcomes",
                belief_id, len(false_outcomes)
            )
            return False

        # === GATE 3: All must be from external ground-truth sources ===
        INTERNAL = frozenset({"self","internal","simulation","agent","agentco_system","twin"})
        internal_src = [p for p in prediction_records if any(s in p.ground_truth_source.lower() for s in INTERNAL)]
        if internal_src:
            logger.warning(
                "FIREWALL BLOCKED: belief %s has %d predictions with internal ground-truth sources",
                belief_id, len(internal_src)
            )
            return False

        # === GATE 4: None may be post_hoc ===
        post_hoc = [p for p in prediction_records if p.post_hoc]
        if post_hoc:
            logger.warning(
                "FIREWALL BLOCKED: belief %s has %d post_hoc predictions",
                belief_id, len(post_hoc)
            )
            return False

        # === NOTE: sim_support_count is INTENTIONALLY IGNORED HERE ===
        # Simulation volume cannot compensate for missing reality contact.

        # ALL GATES PASSED — promote
        belief.validation_status = "reality_validated"
        belief.reality_validated_predictions = [p.prediction_id for p in prediction_records]
        belief.promoted_at = datetime.now(timezone.utc)

        logger.info(
            "FIREWALL PROMOTED: belief %s → reality_validated "
            "(backed by %d reality-scored predictions, sim_count=%d IGNORED)",
            belief_id, len(prediction_records), belief.sim_support_count
        )
        return True

    def get_governing_beliefs(self, domain: Optional[str] = None) -> list[Belief]:
        """Only reality_validated beliefs may govern real decisions."""
        beliefs = [b for b in self._beliefs.values() if b.validation_status == "reality_validated"]
        if domain:
            # In production: filter by domain
            pass
        return beliefs

    def retire(self, belief_id: str, reason: str) -> None:
        belief = self._get_belief(belief_id)
        old_status = belief.validation_status
        belief.validation_status = "retired"
        logger.info("BELIEF RETIRED: id=%s was=%s reason=%s", belief_id, old_status, reason)

    def _get_belief(self, belief_id: str) -> Belief:
        if belief_id not in self._beliefs:
            raise ValueError(f"Belief {belief_id!r} not found")
        return self._beliefs[belief_id]

    def status(self, belief_id: str) -> str:
        return self._get_belief(belief_id).validation_status
