#!/usr/bin/env bash
# Generates .env.live for the local live stack (docker-compose.live.yml).
#
# Idempotent: refuses to overwrite an existing .env.live unless --force is given
# (regenerating rotates every secret, which orphans the API key baked into the
# running stack — always `make live-down` first).
#
# LLM provider selection:
#   - If OPENAI_API_KEY is set in the calling environment, the stack uses the
#     OpenAI API directly.
#   - Otherwise it points at an Ollama server on the Docker host
#     (http://host.docker.internal:11434/v1, model qwen2.5:7b) — install Ollama
#     natively (`brew install ollama`; `ollama pull qwen2.5:7b`) for Metal
#     acceleration. The dummy LLM_API_KEY satisfies the client, which requires a
#     non-empty key; Ollama ignores it.
set -euo pipefail

cd "$(dirname "$0")/../.."
ENV_FILE=".env.live"

if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "[live-init] $ENV_FILE already exists; keeping it (use --force to rotate all secrets)" >&2
else

rand() { openssl rand -hex "$1"; }

PG_PASSWORD="$(rand 24)"

if [[ -n "${OPENAI_API_KEY:-}" ]]; then
  LLM_PROVIDER=openai
  LLM_BASE_URL=https://api.openai.com/v1
  LLM_API_KEY="$OPENAI_API_KEY"
  LLM_MODEL_DEFAULT=gpt-4o-mini
  echo "[live-init] LLM: OpenAI API (key taken from your environment)" >&2
else
  LLM_PROVIDER=ollama
  LLM_BASE_URL=http://host.docker.internal:11434/v1
  LLM_API_KEY=ollama-local-dummy-key
  LLM_MODEL_DEFAULT=qwen2.5:7b
  echo "[live-init] LLM: host Ollama at localhost:11434 (set OPENAI_API_KEY before live-init to use OpenAI instead)" >&2
fi

umask 177
cat > "$ENV_FILE" <<EOF
# Generated by scripts/live/generate_env.sh — DO NOT COMMIT.
# Consumed by docker-compose.live.yml (interpolation + env_file).

# ----- environment posture -----
AGENTCO_ENV=production
NODE_ENV=production
PORT=3001
HOST=0.0.0.0
LOG_LEVEL=info

# ----- database (container-network DSN; host access is 127.0.0.1:5442) -----
LIVE_POSTGRES_PASSWORD=${PG_PASSWORD}
DATABASE_URL=postgresql://agentco:${PG_PASSWORD}@postgres:5432/agentco
RESOLUTION_SERVICE_PASSWORD=$(rand 24)

# ----- kafka / event bus -----
KAFKA_BROKERS=kafka:29092
EVENT_BUS_DELIVERY_MODE=outbox
EVENT_BUS_SIGNING_KEY=$(rand 32)
EVENT_BUS_HMAC_KEY=$(rand 32)

# ----- API + service secrets -----
AGENTCO_API_KEY=$(rand 32)
JWT_SECRET=$(rand 32)
RESERVE_SIGNING_KEY=$(rand 32)
SPECIALIST_SHARED_SECRET=$(rand 32)

# ----- Vault (env-presence check only) -----
# The current backend never opens a Vault connection: runtime-mode.ts only checks
# that VAULT_ADDR/VAULT_TOKEN are set, and secrets are actually read from this
# env file. The .invalid hostname is deliberate — if code ever starts dialing
# Vault for real, it will fail loudly here instead of silently succeeding.
VAULT_ADDR=http://vault-not-deployed.invalid:8200
VAULT_TOKEN=$(rand 16)

# ----- LLM provider -----
LLM_PROVIDER=${LLM_PROVIDER}
LLM_BASE_URL=${LLM_BASE_URL}
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL_DEFAULT=${LLM_MODEL_DEFAULT}
LLM_SEED_BUDGET_TOKENS=5000000
# LLM_RESOURCE_ACTOR_ID / LLM_RESOURCE_ACCOUNT_ID are intentionally absent:
# the backend entrypoint seeds them at boot (dist/cli/seed-live.js --emit-env).

# ----- frontend -----
FRONTEND_URL=http://localhost:3000
EOF

echo "[live-init] wrote $ENV_FILE (mode 600)" >&2

fi
