from scripts.verify_migrations_native import build_report


def test_migration_report_fails_when_required_runtime_columns_missing():
    table_out = "\n".join(
        [
            "agent_task_events",
            "agent_tasks",
            "autonomy_goals",
            "decision_log",
            "departments",
            "eval_runs",
            "eval_scorecards",
            "eval_suites",
            "institution_specialist_assignments",
            "institution_work_requests",
            "learner_candidates",
            "override_queue",
            "prediction_ledger",
            "reward_calculations",
            "reward_functions",
            "specialist_allocation_history",
        ]
    )
    column_out = "\n".join(
        [
            "departments|authority_scope",
            "departments|entity_type",
            "departments|id",
            "departments|metadata",
            "departments|parent_id",
            "eval_runs|id",
            "eval_runs|run_timestamp",
            "eval_runs|status",
            "eval_runs|suite_id",
            "eval_scorecards|eval_run_id",
            "eval_scorecards|id",
            "eval_scorecards|promotion_eligible",
            "eval_suites|active",
            "eval_suites|id",
            "eval_suites|name",
            "institution_work_requests|department_id",
            "institution_work_requests|id",
            "institution_work_requests|institution_id",
            "institution_work_requests|status",
            "institution_specialist_assignments|department_id",
            "institution_specialist_assignments|id",
            "institution_specialist_assignments|institution_id",
            "institution_specialist_assignments|specialist_role",
            "specialist_allocation_history|department_id",
            "specialist_allocation_history|id",
            "specialist_allocation_history|specialist_role",
            "specialist_allocation_history|work_request_id",
            "autonomy_goals|depth",
            "autonomy_goals|goal_depth",
            "autonomy_goals|goal_path",
            "autonomy_goals|id",
            "autonomy_goals|institution_id",
            "autonomy_goals|rollup_status",
            "learner_candidates|artifact_json",
            "learner_candidates|id",
            "learner_candidates|learner_run_id",
            "learner_candidates|simulation_trained",
            "prediction_ledger|consequence",
            "prediction_ledger|prediction_id",
            "reward_calculations|function_id",
            "reward_calculations|id",
            "reward_calculations|metrics_json",
            "reward_calculations|reward_value",
            "reward_functions|function_type",
            "reward_functions|id",
            "reward_functions|name",
        ]
    )

    report = build_report(
        migration_script="ts-node src/db/migrate.ts",
        conn_code=0,
        conn_out="agentco|agentco",
        table_code=0,
        table_out=table_out,
        column_code=0,
        column_out=column_out,
    )

    assert report["success"] is False
    assert report["core_schema_status"] == "missing"
    assert report["missing_columns"] == {
        "departments": ["institution_id"],
        "eval_runs": [
            "baseline_ref",
            "candidate_ref",
            "completed_at",
            "run_status",
            "started_at",
            "target_id",
            "target_type",
            "total_cases",
            "trace_id",
        ],
        "eval_scorecards": ["decision_reason", "overall_score"],
        "eval_suites": ["eval_type", "total_cases"],
        "learner_candidates": ["risk_level"],
        "prediction_ledger": ["hardness"],
        "reward_calculations": [
            "calculation_details_json",
            "components_json",
            "regret_score",
            "reward_function_id",
            "reward_score",
        ],
        "reward_functions": ["created_by", "domain", "formula_json", "owner", "risk_level", "version"],
    }


def test_migration_report_accepts_runtime_required_schema():
    table_out = "\n".join(
        [
            "agent_task_events",
            "agent_tasks",
            "autonomy_goals",
            "decision_log",
            "departments",
            "eval_runs",
            "eval_scorecards",
            "eval_suites",
            "institution_specialist_assignments",
            "institution_work_requests",
            "learner_candidates",
            "override_queue",
            "prediction_ledger",
            "reward_calculations",
            "reward_functions",
            "specialist_allocation_history",
        ]
    )
    column_out = "\n".join(
        [
            "departments|authority_scope",
            "departments|entity_type",
            "departments|id",
            "departments|institution_id",
            "departments|metadata",
            "departments|parent_id",
            "eval_runs|baseline_ref",
            "eval_runs|candidate_ref",
            "eval_runs|completed_at",
            "eval_runs|id",
            "eval_runs|run_status",
            "eval_runs|run_timestamp",
            "eval_runs|started_at",
            "eval_runs|status",
            "eval_runs|suite_id",
            "eval_runs|target_id",
            "eval_runs|target_type",
            "eval_runs|total_cases",
            "eval_runs|trace_id",
            "eval_scorecards|decision_reason",
            "eval_scorecards|eval_run_id",
            "eval_scorecards|id",
            "eval_scorecards|overall_score",
            "eval_scorecards|promotion_eligible",
            "eval_suites|active",
            "eval_suites|eval_type",
            "eval_suites|id",
            "eval_suites|name",
            "eval_suites|total_cases",
            "institution_work_requests|department_id",
            "institution_work_requests|id",
            "institution_work_requests|institution_id",
            "institution_work_requests|status",
            "institution_specialist_assignments|department_id",
            "institution_specialist_assignments|id",
            "institution_specialist_assignments|institution_id",
            "institution_specialist_assignments|specialist_role",
            "specialist_allocation_history|department_id",
            "specialist_allocation_history|id",
            "specialist_allocation_history|specialist_role",
            "specialist_allocation_history|work_request_id",
            "autonomy_goals|depth",
            "autonomy_goals|goal_depth",
            "autonomy_goals|goal_path",
            "autonomy_goals|id",
            "autonomy_goals|institution_id",
            "autonomy_goals|rollup_status",
            "learner_candidates|artifact_json",
            "learner_candidates|id",
            "learner_candidates|learner_run_id",
            "learner_candidates|risk_level",
            "learner_candidates|simulation_trained",
            "prediction_ledger|consequence",
            "prediction_ledger|hardness",
            "prediction_ledger|prediction_id",
            "reward_calculations|calculation_details_json",
            "reward_calculations|components_json",
            "reward_calculations|function_id",
            "reward_calculations|id",
            "reward_calculations|metrics_json",
            "reward_calculations|regret_score",
            "reward_calculations|reward_function_id",
            "reward_calculations|reward_score",
            "reward_calculations|reward_value",
            "reward_functions|created_by",
            "reward_functions|domain",
            "reward_functions|formula_json",
            "reward_functions|function_type",
            "reward_functions|id",
            "reward_functions|name",
            "reward_functions|owner",
            "reward_functions|risk_level",
            "reward_functions|version",
        ]
    )

    report = build_report(
        migration_script="ts-node src/db/migrate.ts",
        conn_code=0,
        conn_out="agentco|agentco",
        table_code=0,
        table_out=table_out,
        column_code=0,
        column_out=column_out,
    )

    assert report["success"] is True
    assert report["missing_tables"] == []
    assert report["missing_columns"] == {}
