-- Migration 143 (AUD-004 M3 breadth): seed ALL permissions introduced by the M3 route-gating
-- pass and grant them to a broad operational role, so requirePrincipal(permission) checks
-- resolve instead of denying every caller with permission_unknown/permission_missing.
--
-- Scope note (honest, not a false claim of least-privilege curation): this remediation pass
-- gated ~170 previously-unauthenticated privileged mutation routes. Assigning each permission
-- to a distinct, carefully-designed human role (citizen vs judge vs treasurer vs institution
-- admin, etc.) is a governance-design exercise beyond AUD-004's scope (authenticate + gate the
-- boundary). This migration seeds every permission and grants the full set to ONE new broad
-- 'civilization_operator' role (in addition to 'governor', which already holds a curated
-- subset from migration 141) so the system is functional and every route requires a real
-- credential-bound grant -- not the previous state of ZERO authentication. Fine-grained,
-- per-role permission curation is flagged as explicit follow-up work in the AUD-004 report.

INSERT INTO roles (role_name, description, risk_tier) VALUES
  ('civilization_operator', 'Broad operational role for authenticated civilization mutation routes (AUD-004 M3 breadth; coarse initial grant, see migration note)', 2)
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permissions (name, description, protected_surface) VALUES
  ('agent.dispatch', 'agent dispatch', NULL),
  ('agent.heartbeat', 'agent heartbeat', NULL),
  ('autonomy.action.execute', 'autonomy action execute', NULL),
  ('autonomy.allocation.record_decision', 'autonomy allocation record decision', NULL),
  ('autonomy.evidence.deduplicate', 'autonomy evidence deduplicate', NULL),
  ('autonomy.evidence.share', 'autonomy evidence share', NULL),
  ('autonomy.goal.create_root', 'autonomy goal create root', NULL),
  ('autonomy.goal.create_sub', 'autonomy goal create sub', NULL),
  ('autonomy.goal.create_task', 'autonomy goal create task', NULL),
  ('autonomy.goal.rollup', 'autonomy goal rollup', NULL),
  ('autonomy.level3.execute', 'autonomy level3 execute', NULL),
  ('autonomy.specialist_team.record_pattern', 'autonomy specialist team record pattern', NULL),
  ('autonomy.task.cancel', 'autonomy task cancel', NULL),
  ('autonomy.task.checkpoint', 'autonomy task checkpoint', NULL),
  ('autonomy.task.complete', 'autonomy task complete', NULL),
  ('autonomy.task.create', 'autonomy task create', NULL),
  ('autonomy.task.fail', 'autonomy task fail', NULL),
  ('autonomy.task.lease', 'autonomy task lease', NULL),
  ('autonomy.task.queue', 'autonomy task queue', NULL),
  ('autonomy.task.start', 'autonomy task start', NULL),
  ('autonomy.work_request.submit', 'autonomy work request submit', NULL),
  ('citizenship.citizen.suspend', 'citizenship citizen suspend', NULL),
  ('citizenship.citizen.transition', 'citizenship citizen transition', NULL),
  ('citizenship.envelope.grant', 'citizenship envelope grant', NULL),
  ('citizenship.role.grant', 'citizenship role grant', NULL),
  ('citizenship.role.revoke', 'citizenship role revoke', NULL),
  ('citizenship.sanction.impose', 'citizenship sanction impose', NULL),
  ('citizenship.sanction.lift', 'citizenship sanction lift', NULL),
  ('citizenship.succession.record', 'citizenship succession record', NULL),
  ('civilization.consistency_check.run', 'civilization consistency check run', NULL),
  ('civilization.kernel.activate', 'civilization kernel activate', NULL),
  ('civilization.kernel.bootstrap', 'civilization kernel bootstrap', NULL),
  ('civilization.kernel.charter.propose', 'civilization kernel charter propose', NULL),
  ('civilization.kernel.create', 'civilization kernel create', NULL),
  ('civilization.kernel.emergency.declare', 'civilization kernel emergency declare', NULL),
  ('civilization.kernel.emergency.revoke', 'civilization kernel emergency revoke', NULL),
  ('civilization.kernel.objective.create', 'civilization kernel objective create', NULL),
  ('civilization.kernel.objective.status', 'civilization kernel objective status', NULL),
  ('civilization.kernel.transition', 'civilization kernel transition', NULL),
  ('civilization_os.daemon.start', 'civilization os daemon start', NULL),
  ('civilization_os.daemon.stop', 'civilization os daemon stop', NULL),
  ('civilization_os.mode.set', 'civilization os mode set', NULL),
  ('civilization_os.tick.trigger', 'civilization os tick trigger', NULL),
  ('coalition.activate', 'coalition activate', NULL),
  ('coalition.commitment.commit', 'coalition commitment commit', NULL),
  ('coalition.consensus.resolve', 'coalition consensus resolve', NULL),
  ('coalition.constitute', 'coalition constitute', NULL),
  ('coalition.delegation.grant', 'coalition delegation grant', NULL),
  ('coalition.dissent.record', 'coalition dissent record', NULL),
  ('coalition.negotiate', 'coalition negotiate', NULL),
  ('coalition.proposal.submit', 'coalition proposal submit', NULL),
  ('coalition.propose', 'coalition propose', NULL),
  ('coalition.settle', 'coalition settle', NULL),
  ('coalition.terminate', 'coalition terminate', NULL),
  ('constitution.activate', 'constitution activate', NULL),
  ('constitution.validate_change', 'constitution validate change', NULL),
  ('constitution.version.create', 'constitution version create', NULL),
  ('evolution.approve', 'evolution approve', NULL),
  ('evolution.canary.report', 'evolution canary report', NULL),
  ('evolution.canary.start', 'evolution canary start', NULL),
  ('evolution.candidate.generate_regressions', 'evolution candidate generate regressions', NULL),
  ('evolution.candidate.mark_sandboxed', 'evolution candidate mark sandboxed', NULL),
  ('evolution.candidate.propose', 'evolution candidate propose', NULL),
  ('evolution.candidate.record_failure_analysis', 'evolution candidate record failure analysis', NULL),
  ('evolution.candidate.retain', 'evolution candidate retain', NULL),
  ('evolution.candidate.rollback', 'evolution candidate rollback', NULL),
  ('evolution.evaluate', 'evolution evaluate', NULL),
  ('expansion.capability.grant', 'expansion capability grant', NULL),
  ('expansion.capability.restrict', 'expansion capability restrict', NULL),
  ('expansion.capability.revoke', 'expansion capability revoke', NULL),
  ('expansion.proposal.approve', 'expansion proposal approve', NULL),
  ('expansion.proposal.propose', 'expansion proposal propose', NULL),
  ('expansion.proposal.stage', 'expansion proposal stage', NULL),
  ('goal.lock.acquire', 'goal lock acquire', NULL),
  ('goal.lock.release', 'goal lock release', NULL),
  ('governance.assessment.create', 'governance assessment create', NULL),
  ('governance.canary.metric', 'governance canary metric', NULL),
  ('governance.canary.promote', 'governance canary promote', NULL),
  ('governance.canary.rollback', 'governance canary rollback', NULL),
  ('governance.canary.start', 'governance canary start', NULL),
  ('governance.change.approve', 'governance change approve', NULL),
  ('governance.change.request', 'governance change request', NULL),
  ('governance.change.review', 'governance change review', NULL),
  ('governance.deliberation.open', 'governance deliberation open', NULL),
  ('governance.deliberation.record', 'governance deliberation record', NULL),
  ('governance.drift.detect', 'governance drift detect', NULL),
  ('governance.drift.resolve', 'governance drift resolve', NULL),
  ('governance.emergency_power.expire_sweep', 'governance emergency power expire sweep', NULL),
  ('governance.emergency_power.grant', 'governance emergency power grant', NULL),
  ('governance.policy.evaluate', 'governance policy evaluate', NULL),
  ('governance.policy.rollback', 'governance policy rollback', NULL),
  ('governance.proposal.activate', 'governance proposal activate', NULL),
  ('governance.proposal.create', 'governance proposal create', NULL),
  ('governance.proposal.impact_assess', 'governance proposal impact assess', NULL),
  ('governance.proposal.sponsor', 'governance proposal sponsor', NULL),
  ('governance.reputation.record', 'governance reputation record', NULL),
  ('governance.runtime.dispatch_tick', 'governance runtime dispatch tick', NULL),
  ('governance.runtime.reachability_tick', 'governance runtime reachability tick', NULL),
  ('governance.scheduler.run_once', 'governance scheduler run once', NULL),
  ('governance.scheduler.start', 'governance scheduler start', NULL),
  ('governance.scheduler.stop', 'governance scheduler stop', NULL),
  ('governance.vote', 'governance vote', NULL),
  ('governance.voting.close', 'governance voting close', NULL),
  ('governance.voting.open', 'governance voting open', NULL),
  ('identity.delegation.grant', 'identity delegation grant', NULL),
  ('identity.key.register', 'identity key register', NULL),
  ('identity.key.revoke', 'identity key revoke', NULL),
  ('identity.permission.grant', 'identity permission grant', NULL),
  ('identity.role.assign', 'identity role assign', NULL),
  ('institution.bootstrap_mandatory', 'institution bootstrap mandatory', NULL),
  ('institution.charter.propose', 'institution charter propose', NULL),
  ('institution.contract.propose', 'institution contract propose', NULL),
  ('institution.contract.transition', 'institution contract transition', NULL),
  ('institution.jurisdiction.grant', 'institution jurisdiction grant', NULL),
  ('institution.limit.set', 'institution limit set', NULL),
  ('institution.mandate.grant', 'institution mandate grant', NULL),
  ('institution.power.grant', 'institution power grant', NULL),
  ('institution.specialist.assign', 'institution specialist assign', NULL),
  ('judiciary.appeal.decide', 'judiciary appeal decide', NULL),
  ('judiciary.appeal.file', 'judiciary appeal file', NULL),
  ('judiciary.case.finalize', 'judiciary case finalize', NULL),
  ('judiciary.case.open', 'judiciary case open', NULL),
  ('judiciary.dissent.record', 'judiciary dissent record', NULL),
  ('judiciary.enforcement.issue', 'judiciary enforcement issue', NULL),
  ('judiciary.evidence.submit', 'judiciary evidence submit', NULL),
  ('judiciary.evidence_collection.open', 'judiciary evidence collection open', NULL),
  ('judiciary.hearing.hold', 'judiciary hearing hold', NULL),
  ('judiciary.jurisdiction.check', 'judiciary jurisdiction check', NULL),
  ('judiciary.ruling.issue', 'judiciary ruling issue', NULL),
  ('knowledge.provenance.link', 'knowledge provenance link', NULL),
  ('knowledge.retraction.create', 'knowledge retraction create', NULL),
  ('mission.complete', 'mission complete', NULL),
  ('mission.create', 'mission create', NULL),
  ('mission.dependency.add', 'mission dependency add', NULL),
  ('mission.evidence.link', 'mission evidence link', NULL),
  ('mission.outcome.record', 'mission outcome record', NULL),
  ('mission.settle', 'mission settle', NULL),
  ('mission.settlement.record', 'mission settlement record', NULL),
  ('mission.strategic_goal.create', 'mission strategic goal create', NULL),
  ('mission.task.add', 'mission task add', NULL),
  ('mission.task.record_attempt', 'mission task record attempt', NULL),
  ('mission.transition', 'mission transition', NULL),
  ('mission.workstream.add', 'mission workstream add', NULL),
  ('mission.workstream.complete', 'mission workstream complete', NULL),
  ('override.enqueue', 'override enqueue', NULL),
  ('override.resolve', 'override resolve', NULL),
  ('reputation.batch_update', 'reputation batch update', NULL),
  ('resource.account.create', 'resource account create', NULL),
  ('resource.reservation.create', 'resource reservation create', NULL),
  ('resource.reservation.release', 'resource reservation release', NULL),
  ('resource.reservation.settle', 'resource reservation settle', NULL),
  ('resource.transaction.credit', 'resource transaction credit', NULL),
  ('resource.transaction.debit', 'resource transaction debit', NULL),
  ('society.bootstrap_defaults', 'society bootstrap defaults', NULL),
  ('society.citizen.join', 'society citizen join', NULL),
  ('society.citizen.leave', 'society citizen leave', NULL),
  ('society.create', 'society create', NULL),
  ('society.institution.attach', 'society institution attach', NULL),
  ('society.jurisdiction.grant', 'society jurisdiction grant', NULL),
  ('society.transition', 'society transition', NULL),
  ('treasury.account.fund', 'treasury account fund', NULL),
  ('treasury.account.open', 'treasury account open', NULL),
  ('treasury.budget.allocate', 'treasury budget allocate', NULL),
  ('treasury.budget.decide', 'treasury budget decide', NULL),
  ('treasury.budget.propose', 'treasury budget propose', NULL),
  ('treasury.cost.record', 'treasury cost record', NULL),
  ('treasury.penalty.impose', 'treasury penalty impose', NULL),
  ('treasury.policy.set', 'treasury policy set', NULL),
  ('treasury.reconcile', 'treasury reconcile', NULL),
  ('treasury.request.evaluate', 'treasury request evaluate', NULL),
  ('trust_policy.approve', 'trust policy approve', NULL),
  ('trust_policy.create', 'trust policy create', NULL),
  ('trust_policy.review', 'trust policy review', NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, '*'
  FROM roles r, permissions p
 WHERE r.role_name = 'civilization_operator'
   AND p.name IN ('agent.dispatch', 'agent.heartbeat', 'autonomy.action.execute', 'autonomy.allocation.record_decision', 'autonomy.evidence.deduplicate', 'autonomy.evidence.share', 'autonomy.goal.create_root', 'autonomy.goal.create_sub', 'autonomy.goal.create_task', 'autonomy.goal.rollup', 'autonomy.level3.execute', 'autonomy.specialist_team.record_pattern', 'autonomy.task.cancel', 'autonomy.task.checkpoint', 'autonomy.task.complete', 'autonomy.task.create', 'autonomy.task.fail', 'autonomy.task.lease', 'autonomy.task.queue', 'autonomy.task.start', 'autonomy.work_request.submit', 'citizenship.citizen.suspend', 'citizenship.citizen.transition', 'citizenship.envelope.grant', 'citizenship.role.grant', 'citizenship.role.revoke', 'citizenship.sanction.impose', 'citizenship.sanction.lift', 'citizenship.succession.record', 'civilization.consistency_check.run', 'civilization.kernel.activate', 'civilization.kernel.bootstrap', 'civilization.kernel.charter.propose', 'civilization.kernel.create', 'civilization.kernel.emergency.declare', 'civilization.kernel.emergency.revoke', 'civilization.kernel.objective.create', 'civilization.kernel.objective.status', 'civilization.kernel.transition', 'civilization_os.daemon.start', 'civilization_os.daemon.stop', 'civilization_os.mode.set', 'civilization_os.tick.trigger', 'coalition.activate', 'coalition.commitment.commit', 'coalition.consensus.resolve', 'coalition.constitute', 'coalition.delegation.grant', 'coalition.dissent.record', 'coalition.negotiate', 'coalition.proposal.submit', 'coalition.propose', 'coalition.settle', 'coalition.terminate', 'constitution.activate', 'constitution.validate_change', 'constitution.version.create', 'evolution.approve', 'evolution.canary.report', 'evolution.canary.start', 'evolution.candidate.generate_regressions', 'evolution.candidate.mark_sandboxed', 'evolution.candidate.propose', 'evolution.candidate.record_failure_analysis', 'evolution.candidate.retain', 'evolution.candidate.rollback', 'evolution.evaluate', 'expansion.capability.grant', 'expansion.capability.restrict', 'expansion.capability.revoke', 'expansion.proposal.approve', 'expansion.proposal.propose', 'expansion.proposal.stage', 'goal.lock.acquire', 'goal.lock.release', 'governance.assessment.create', 'governance.canary.metric', 'governance.canary.promote', 'governance.canary.rollback', 'governance.canary.start', 'governance.change.approve', 'governance.change.request', 'governance.change.review', 'governance.deliberation.open', 'governance.deliberation.record', 'governance.drift.detect', 'governance.drift.resolve', 'governance.emergency_power.expire_sweep', 'governance.emergency_power.grant', 'governance.policy.evaluate', 'governance.policy.rollback', 'governance.proposal.activate', 'governance.proposal.create', 'governance.proposal.impact_assess', 'governance.proposal.sponsor', 'governance.reputation.record', 'governance.runtime.dispatch_tick', 'governance.runtime.reachability_tick', 'governance.scheduler.run_once', 'governance.scheduler.start', 'governance.scheduler.stop', 'governance.vote', 'governance.voting.close', 'governance.voting.open', 'identity.delegation.grant', 'identity.key.register', 'identity.key.revoke', 'identity.permission.grant', 'identity.role.assign', 'institution.bootstrap_mandatory', 'institution.charter.propose', 'institution.contract.propose', 'institution.contract.transition', 'institution.jurisdiction.grant', 'institution.limit.set', 'institution.mandate.grant', 'institution.power.grant', 'institution.specialist.assign', 'judiciary.appeal.decide', 'judiciary.appeal.file', 'judiciary.case.finalize', 'judiciary.case.open', 'judiciary.dissent.record', 'judiciary.enforcement.issue', 'judiciary.evidence.submit', 'judiciary.evidence_collection.open', 'judiciary.hearing.hold', 'judiciary.jurisdiction.check', 'judiciary.ruling.issue', 'knowledge.provenance.link', 'knowledge.retraction.create', 'mission.complete', 'mission.create', 'mission.dependency.add', 'mission.evidence.link', 'mission.outcome.record', 'mission.settle', 'mission.settlement.record', 'mission.strategic_goal.create', 'mission.task.add', 'mission.task.record_attempt', 'mission.transition', 'mission.workstream.add', 'mission.workstream.complete', 'override.enqueue', 'override.resolve', 'reputation.batch_update', 'resource.account.create', 'resource.reservation.create', 'resource.reservation.release', 'resource.reservation.settle', 'resource.transaction.credit', 'resource.transaction.debit', 'society.bootstrap_defaults', 'society.citizen.join', 'society.citizen.leave', 'society.create', 'society.institution.attach', 'society.jurisdiction.grant', 'society.transition', 'treasury.account.fund', 'treasury.account.open', 'treasury.budget.allocate', 'treasury.budget.decide', 'treasury.budget.propose', 'treasury.cost.record', 'treasury.penalty.impose', 'treasury.policy.set', 'treasury.reconcile', 'treasury.request.evaluate', 'trust_policy.approve', 'trust_policy.create', 'trust_policy.review')
ON CONFLICT (role_id, permission_id, scope) DO NOTHING;

