#!/usr/bin/env python3
"""Generate forensic audit control ledgers.

The output is intentionally conservative. It separates inventory coverage from
line-level audit completion and prevents a future report from calling the audit
complete without explicit accounting for requirements, integrations, claims, and
external dependencies.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "docs" / "audit" / "FORENSIC_AUDIT_CONTROLS.json"
OUT_MD = ROOT / "docs" / "audit" / "FORENSIC_AUDIT_CONTROLS.md"

PURPOSE = (
    "AgentCo exists to evolve into progressively more general intelligence by "
    "operating as an evidence-governed, calibration-driven AI civilization "
    "that learns continuously, improves itself safely, and expands its "
    "capability across domains over time."
)


def run(args: list[str]) -> str:
    return subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True).stdout


def git_files() -> list[str]:
    return [line for line in run(["git", "ls-files"]).splitlines() if line]


def exists(path: str) -> bool:
    return (ROOT / path).exists()


def text_contains(path: str, needle: str) -> bool:
    candidate = ROOT / path
    return candidate.exists() and needle in candidate.read_text(encoding="utf-8")


def requirement_rows() -> list[dict[str, str]]:
    return [
        {
            "id": "REQ-001",
            "capability": "Governed active-agent execution",
            "who_needs_it": "Operators and users invoking production agents",
            "trigger": "Backend route, TS identity, or agent manifest entrypoint invokes an active agent",
            "input_output": "Governed action request -> audited success/failure with evidence and spend context",
            "success_criteria": "Unauthorized execution rejected; allowed execution audited; undeclared tools blocked",
            "failure_expectations": "Failures are finalized and audit-chained; no direct ledger writes",
            "implementing_workflow": "backend/src/services/agent-runtime-registry.service.ts + docs/audit/AGENT_PROTOCOL_CONFORMANCE_MATRIX.json",
            "test_evidence": "backend/tests/agent-protocol-conformance.test.ts",
            "production_evidence": "make release-gate runs agent-protocol-matrix-check",
            "status": "verified_with_release_gate",
        },
        {
            "id": "REQ-002",
            "capability": "Tamper-evident audit protocol",
            "who_needs_it": "Governance, evaluation, learning, experiment, and operator audit flows",
            "trigger": "Any governed action or protocol writer appends decision_log",
            "input_output": "Audit event + attempt_id -> idempotent decision_log row with hash-chain link",
            "success_criteria": "Versioned rows reject legacy hashes, missing post-cutoff versions, and tampered versions",
            "failure_expectations": "Write or ACK failures fail closed unless retry confirms the same attempt_id row",
            "implementing_workflow": "backend/src/services/audit-chain.service.ts + agents/core/audit_writer.py",
            "test_evidence": "backend/tests/audit-chain-cross-writer.test.ts",
            "production_evidence": "make release-gate runs audit-chain-cross-writer.test.ts when DB is available",
            "status": "configuration_dependent_live_db",
        },
        {
            "id": "REQ-003",
            "capability": "Evaluation and calibration enforcement",
            "who_needs_it": "Owners deciding whether outputs are correct, supported, and calibrated",
            "trigger": "Benchmark/evaluation suite evaluates active-agent categories",
            "input_output": "Agent output + evidence + confidence -> immutable evaluation record and metrics",
            "success_criteria": "Unsupported high-confidence and tampered evidence fail; calibration metrics reproduce",
            "failure_expectations": "Self-certification rejected without deterministic verification",
            "implementing_workflow": "backend/src/services/evaluation-calibration.service.ts",
            "test_evidence": "backend/tests/evaluation-calibration.test.ts",
            "production_evidence": "docs/audit/EVALUATION_CALIBRATION_REPORT.json generated by release gate",
            "status": "verified_with_release_gate",
        },
        {
            "id": "REQ-004",
            "capability": "Controlled learning with rollback",
            "who_needs_it": "Operators promoting evaluated improvements",
            "trigger": "A learning artifact is proposed, evaluated, approved, promoted, or rolled back",
            "input_output": "Artifact + evaluation evidence + approval -> staged promotion or rejection",
            "success_criteria": "Phase 10 evidence required; self-approval rejected; rollback recovers previous version",
            "failure_expectations": "Regressions or tampered evidence block promotion and are audited",
            "implementing_workflow": "backend/src/services/controlled-learning.service.ts",
            "test_evidence": "backend/tests/controlled-learning.test.ts",
            "production_evidence": "docs/audit/CONTROLLED_LEARNING_REPORT.json generated by release gate",
            "status": "verified_with_release_gate",
        },
        {
            "id": "REQ-005",
            "capability": "Bounded self-improvement experiments",
            "who_needs_it": "Teams evaluating prompt/policy/tool/memory/model-routing changes safely",
            "trigger": "Experiment proposal submitted through governed experiment service",
            "input_output": "Hypothesis + scope + budgets + evidence -> audited experiment result and promotion recommendation",
            "success_criteria": "Sandbox-only, resource-bounded, no production mutation, no self-promotion",
            "failure_expectations": "Scope escape, budget overrun, unauthorized tools, and tampered evidence fail durably",
            "implementing_workflow": "backend/src/services/self-improvement-experiment.service.ts",
            "test_evidence": "backend/tests/self-improvement-experiment.test.ts",
            "production_evidence": "docs/audit/SELF_IMPROVEMENT_EXPERIMENT_REPORT.json generated by release gate",
            "status": "verified_with_release_gate",
        },
        {
            "id": "REQ-006",
            "capability": "Production deployment topology",
            "who_needs_it": "Operators deploying AgentCo to Kubernetes",
            "trigger": "Helm install/upgrade or deploy workflow",
            "input_output": "Versioned images + secrets + values -> backend, frontend, migration, and outbox workloads",
            "success_criteria": "Health probes target real endpoints; migrations run once; frontend/API services route correctly",
            "failure_expectations": "Missing mandatory secrets fail pod/job startup rather than silently selecting fake adapters",
            "implementing_workflow": "infrastructure/kubernetes/helm/agentco/templates/*.yaml",
            "test_evidence": "backend/tests/helm-deployment-contract.test.ts",
            "production_evidence": "Helm render remains externally unverified where helm binary is unavailable",
            "status": "verified_static_unverified_helm_render",
        },
        {
            "id": "REQ-007",
            "capability": "Secure browser/backend authentication boundary",
            "who_needs_it": "Browser users and service-to-service clients",
            "trigger": "Frontend request to backend API dependency",
            "input_output": "User/session or server-side proxy request -> authorized backend response",
            "success_criteria": "Privileged API keys never appear in browser bundle; protected routes reject missing credentials",
            "failure_expectations": "Invalid auth returns sanitized 401/403; service keys remain server-side",
            "implementing_workflow": "frontend/src/app/api/agentco/[...path]/route.ts + backend auth hook",
            "test_evidence": "scripts/smoke_frontend_auth.sh + backend route-auth contract tests",
            "production_evidence": "make release-gate includes frontend auth smoke where services are available",
            "status": "configuration_dependent_runtime",
        },
        {
            "id": "REQ-008",
            "capability": "Operational recoverability",
            "who_needs_it": "Operators responding to database, event, deployment, or rollback failure",
            "trigger": "Backup, restore, release, rollback, or incident procedure",
            "input_output": "Runbook command -> verified backup/restore/rollback signal",
            "success_criteria": "Commands exist, avoid secrets in source, and document external prerequisites",
            "failure_expectations": "Unavailable external infrastructure is reported as unverified, not success",
            "implementing_workflow": "scripts/test_staging_dr.sh + README operations sections",
            "test_evidence": "make verify-clean-room and release-gate checks",
            "production_evidence": "Live cluster restore remains externally unverified without cluster/credentials",
            "status": "partially_verified_external",
        },
    ]


def external_dependencies() -> list[dict[str, str]]:
    return [
        {
            "name": "PostgreSQL",
            "type": "database",
            "consumer": "backend runtime, migrations, Python audit writers, release gate",
            "configuration": "DATABASE_URL, RELEASE_GATE_DATABASE_URL, MIGRATION_DATABASE_URL",
            "classification": "configuration_dependent",
            "evidence": "backend/src/db/migrate.ts; Makefile release-gate; Helm migration job",
        },
        {
            "name": "Redis",
            "type": "cache/coordination",
            "consumer": "backend readiness and runtime services",
            "configuration": "REDIS_URL; Helm redis.auth.existingSecret",
            "classification": "configuration_dependent",
            "evidence": "infrastructure/kubernetes/helm/agentco/values.yaml",
        },
        {
            "name": "Kafka",
            "type": "queue/event broker",
            "consumer": "event bus, outbox worker, readiness when mandatory",
            "configuration": "KAFKA_BROKERS, KAFKA_MANDATORY",
            "classification": "configuration_dependent",
            "evidence": "backend/src/workers/outbox-worker.ts; backend/tests/health-contract.test.ts",
        },
        {
            "name": "OpenAI-compatible LLM provider",
            "type": "model provider",
            "consumer": "central LLM service",
            "configuration": "LLM_BASE_URL, LLM_API_KEY, LLM_RESOURCE_ACTOR_ID, LLM_RESOURCE_ACCOUNT_ID",
            "classification": "configuration_dependent",
            "evidence": "backend Helm env; LLM budget contract tests",
        },
        {
            "name": "Vault",
            "type": "secret management",
            "consumer": "backend production configuration",
            "configuration": "VAULT_ADDR, VAULT_TOKEN",
            "classification": "assumed_external",
            "evidence": "Helm secret refs; live Vault connectivity not verified in local gate",
        },
        {
            "name": "Pinecone",
            "type": "vector store",
            "consumer": "optional memory/vector integrations",
            "configuration": "PINECONE_API_KEY, PINECONE_ENVIRONMENT, PINECONE_INDEX_NAME",
            "classification": "optional_unavailable",
            "evidence": "Helm marks Pinecone secret refs optional",
        },
        {
            "name": "Kubernetes cluster and Helm",
            "type": "deployment infrastructure",
            "consumer": "deploy workflow and operators",
            "configuration": "KUBECONFIG, Helm values, Kubernetes Secrets",
            "classification": "externally_unverified_locally",
            "evidence": ".github/workflows/deploy.yml; infrastructure/kubernetes/helm/agentco",
        },
        {
            "name": "GitHub Container Registry",
            "type": "image registry",
            "consumer": "deploy workflow and Kubernetes image pulls",
            "configuration": "GITHUB_TOKEN, imagePullSecrets",
            "classification": "assumed_external",
            "evidence": ".github/workflows/deploy.yml; Helm global.imagePullSecrets",
        },
    ]


def workflow_rows() -> list[dict[str, str]]:
    return [
        {
            "workflow": "Production deploy",
            "entrypoint": ".github/workflows/deploy.yml -> Helm chart",
            "status": "partially_verified_static",
            "test_evidence": "backend/tests/helm-deployment-contract.test.ts",
        },
        {
            "workflow": "Release gate",
            "entrypoint": "make release-gate",
            "status": "verified_when_executed",
            "test_evidence": "Makefile",
        },
        {
            "workflow": "Agent execution",
            "entrypoint": "backend registry/factory and active-agent manifest",
            "status": "verified_by_conformance",
            "test_evidence": "agent-protocol-matrix-check",
        },
        {
            "workflow": "Audit chain append/verify",
            "entrypoint": "TS/Python audit writers",
            "status": "configuration_dependent_live_db",
            "test_evidence": "audit-chain-cross-writer.test.ts",
        },
        {
            "workflow": "Evaluation/calibration",
            "entrypoint": "evaluation report generator and service",
            "status": "verified_by_report_and_tests",
            "test_evidence": "evaluation-calibration-report-check",
        },
        {
            "workflow": "Controlled learning promotion/rollback",
            "entrypoint": "controlled learning service/report generator",
            "status": "verified_by_report_and_tests",
            "test_evidence": "controlled-learning-report-check",
        },
        {
            "workflow": "Bounded self-improvement experiment",
            "entrypoint": "self-improvement service/report generator",
            "status": "verified_by_report_and_tests",
            "test_evidence": "self-improvement-report-check",
        },
        {
            "workflow": "Frontend API dependency request",
            "entrypoint": "Next app/API proxy",
            "status": "configuration_dependent_runtime",
            "test_evidence": "scripts/smoke_frontend_auth.sh",
        },
    ]


def claim_rows() -> list[dict[str, str]]:
    return [
        {
            "claim": PURPOSE,
            "implementation_evidence": "Active-agent conformance, evaluation/calibration, controlled-learning, and self-improvement reports",
            "runtime_entrypoint": "make release-gate plus production backend/Helm deployment",
            "classification": "verified_with_limitations",
            "limitation": "General intelligence and continuous improvement are roadmap intent; verified behavior is bounded governed execution and evaluated promotion controls.",
        },
        {
            "claim": "A stranger can run the credibility gate.",
            "implementation_evidence": "Makefile release-gate and verify-clean-room targets",
            "runtime_entrypoint": "make release-gate",
            "classification": "verified_when_command_passes",
            "limitation": "DB/Kafka-backed parts are capability-probed or require local services.",
        },
        {
            "claim": "Kubernetes deployment exists.",
            "implementation_evidence": "Backend, frontend, service, ingress, migration, outbox worker templates",
            "runtime_entrypoint": "helm upgrade --install",
            "classification": "partially_verified",
            "limitation": "Helm binary/cluster not available in this environment for render/apply proof.",
        },
        {
            "claim": "Browser does not receive privileged service API key.",
            "implementation_evidence": "Frontend proxy uses server-side AGENTCO_API_KEY; Helm frontend template avoids NEXT_PUBLIC_AGENTCO_API_KEY",
            "runtime_entrypoint": "frontend/src/app/api/agentco/[...path]/route.ts",
            "classification": "verified_static_and_smoke",
            "limitation": "Full deployed browser bundle scan depends on production build artifact.",
        },
    ]


def main() -> int:
    files = git_files()
    tests = [p for p in files if p.startswith("tests/") or "/tests/" in p or Path(p).name.startswith("test_")]
    workflows = workflow_rows()
    claims = claim_rows()
    requirements = requirement_rows()
    dependencies = external_dependencies()

    completeness = {
        "total_files_discovered": len(files),
        "files_inventoried": len(files) if exists("docs/audit/FORENSIC_FILE_INVENTORY.json") else 0,
        "files_line_audited": 0,
        "files_excluded": 0,
        "file_audit_note": "All tracked files are inventoried. Line-level review is intentionally not marked complete by this generated control ledger.",
        "tests_discovered": len(tests),
        "workflows_discovered": len(workflows),
        "workflows_tested_or_gated": sum(1 for w in workflows if w["test_evidence"]),
        "integrations_discovered": len(dependencies),
        "integrations_verified_without_external_dependency": sum(
            1 for d in dependencies if d["classification"] in {"verified", "optional_unavailable"}
        ),
        "claims_discovered": len(claims),
        "claims_proven_or_limited": sum(
            1 for c in claims if c["classification"] in {"verified_static_and_smoke", "verified_with_limitations", "verified_when_command_passes"}
        ),
        "requirements_discovered": len(requirements),
        "requirements_with_test_evidence": sum(1 for r in requirements if r["test_evidence"]),
    }

    post_remediation_reaudit = [
        {
            "check": "New regressions",
            "method": "Run release gate and focused contract tests after remediation.",
            "status": "required_before_final_verdict",
        },
        {
            "check": "Tests weakened during remediation",
            "method": "Review git diff for removed assertions, new skips, xfails, or force exits.",
            "status": "required_before_final_verdict",
        },
        {
            "check": "Documentation drift",
            "method": "Compare README/Helm/Makefile commands to actual targets and tests.",
            "status": "required_before_final_verdict",
        },
        {
            "check": "Temporary bridges and duplicated architecture",
            "method": "Search for TODO/FIXME/stub/mock/fallback and classify remaining hits.",
            "status": "required_before_final_verdict",
        },
        {
            "check": "Resolved finding accuracy",
            "method": "Re-run original reproduction checks and ensure new tests fail on the old behavior.",
            "status": "required_before_final_verdict",
        },
    ]

    payload = {
        "generated_by": "scripts/generate_forensic_audit_controls.py",
        "repository_purpose": PURPOSE,
        "requirements_to_behaviour_matrix": requirements,
        "external_dependency_audit": dependencies,
        "workflow_coverage": workflows,
        "claim_to_evidence_matrix": claims,
        "finding_completeness_ledger": completeness,
        "independent_post_remediation_reaudit": post_remediation_reaudit,
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Forensic Audit Controls",
        "",
        f"Repository purpose: {PURPOSE}",
        "",
        "## Requirements-To-Behaviour Matrix",
        "",
        "| ID | Capability | Who needs it | Trigger | Input/output | Success criteria | Failure expectations | Workflow | Test evidence | Production evidence | Status |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in requirements:
        lines.append(
            "| {id} | {capability} | {who_needs_it} | {trigger} | {input_output} | {success_criteria} | {failure_expectations} | {implementing_workflow} | {test_evidence} | {production_evidence} | {status} |".format(
                **row
            )
        )
    lines.extend([
        "",
        "## Cross-Repository And External Dependency Audit",
        "",
        "| Name | Type | Consumer | Configuration | Classification | Evidence |",
        "|---|---|---|---|---|---|",
    ])
    for dep in dependencies:
        lines.append(
            f"| {dep['name']} | {dep['type']} | {dep['consumer']} | {dep['configuration']} | {dep['classification']} | {dep['evidence']} |"
        )
    lines.extend([
        "",
        "## Finding Completeness Ledger",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ])
    for key, value in completeness.items():
        lines.append(f"| {key} | {value} |")
    lines.extend([
        "",
        "## Initial Claim-To-Evidence Matrix",
        "",
        "| Claim | Implementation evidence | Runtime entrypoint | Classification | Limitation |",
        "|---|---|---|---|---|",
    ])
    for claim in claims:
        lines.append(
            f"| {claim['claim']} | {claim['implementation_evidence']} | {claim['runtime_entrypoint']} | {claim['classification']} | {claim['limitation']} |"
        )
    lines.extend([
        "",
        "## Independent Post-Remediation Re-Audit Checklist",
        "",
        "| Check | Method | Status |",
        "|---|---|---|",
    ])
    for item in post_remediation_reaudit:
        lines.append(f"| {item['check']} | {item['method']} | {item['status']} |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_JSON.relative_to(ROOT)} and {OUT_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
