#!/usr/bin/env python3
"""Generate README implementation status from BUILD_LEDGER.yaml."""
from __future__ import annotations

import subprocess
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
LEDGER_PATH = ROOT / "BUILD_LEDGER.yaml"
README_PATH = ROOT / "README.md"

BEGIN = "<!-- STATUS:BEGIN (generated by scripts/generate_status.py — do not edit) -->"
END = "<!-- STATUS:END -->"


def _ledger_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", str(LEDGER_PATH.relative_to(ROOT))],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return result.stdout.strip() or "unknown"


def _load_ledger() -> dict:
    with LEDGER_PATH.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{LEDGER_PATH} must contain a YAML mapping")
    return data


def _render_status(ledger: dict) -> str:
    meta = ledger.get("meta") or {}
    rollups = ledger.get("rollups") or {}

    verified = rollups["verified"]
    total = rollups["total_items"]
    percent = rollups["percent_verified"]
    termination = bool(meta.get("termination_predicate_met"))
    generated_at = meta.get("last_updated", "unknown")

    return "\n".join(
        [
            BEGIN,
            "",
            "| Field | Value |",
            "|---|---|",
            f"| Verified items | `{verified}/{total} ({percent}%)` |",
            f"| Termination predicate met | `{str(termination).lower()}` |",
            f"| Generated from ledger timestamp | `{generated_at}` |",
            f"| Build ledger commit | `{_ledger_commit()}` |",
            "",
            END,
        ]
    )


def _inject(readme: str, block: str) -> str:
    start = readme.find(BEGIN)
    end = readme.find(END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            f"{README_PATH} must contain {BEGIN!r} and {END!r} markers"
        )
    end += len(END)
    return readme[:start] + block + readme[end:]


def main() -> int:
    ledger = _load_ledger()
    block = _render_status(ledger)
    current = README_PATH.read_text(encoding="utf-8")
    updated = _inject(current, block)
    if updated != current:
        README_PATH.write_text(updated, encoding="utf-8")
        print(f"Updated {README_PATH.relative_to(ROOT)}")
    else:
        print(f"{README_PATH.relative_to(ROOT)} already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
